-- Fairburn / South Fulton outreach prospect list for the sales team.
--
-- Distinct from `local_businesses`: that table is an automated ingest of new
-- business-license filings across South Atlanta ZIPs (which do not include
-- Fairburn's 30213). This one is a hand-curated, tiered call list with a
-- product angle and outreach status per row, worked by the shop directly.
--
-- Tiers: A = recurring apparel need (churches, schools, daycares, trades,
-- shops), B = staff/promo orders, C = large volume but a long sales cycle
-- (warehouses, city, chamber).
--
-- phone_confidence records how a number was sourced, so nobody dials a
-- half-matched listing believing it was confirmed:
--   verified       - business name AND street address agreed across two sources
--   verify on call - name matched strongly, listed address differed
--   map listing    - single mapping source only
-- A NULL phone means no number could be matched honestly. Left blank on
-- purpose; a wrong number on a call sheet costs more than a blank one.

CREATE TABLE IF NOT EXISTS prospects (
  id                SERIAL PRIMARY KEY,
  tier              CHAR(1) NOT NULL DEFAULT 'B' CHECK (tier IN ('A','B','C')),
  name              VARCHAR(255) NOT NULL,
  category          VARCHAR(120),
  address           VARCHAR(255),
  city              VARCHAR(120),
  phone             VARCHAR(40),
  phone_confidence  VARCHAR(20),
  google_rating     VARCHAR(20),
  product_angle     TEXT,
  notes             TEXT,
  -- Outreach tracking, owned by the sales team.
  status            VARCHAR(20) NOT NULL DEFAULT 'new'
                      CHECK (status IN ('new','contacted','quoted','won','lost')),
  contact_name      VARCHAR(160),
  contact_email     VARCHAR(255),
  outreach_notes    TEXT,
  last_contacted_at TIMESTAMP WITH TIME ZONE,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Name is the natural key for the seed re-run guard below.
CREATE UNIQUE INDEX IF NOT EXISTS idx_prospects_name ON prospects (name);
CREATE INDEX IF NOT EXISTS idx_prospects_tier_status ON prospects (tier, status);
CREATE INDEX IF NOT EXISTS idx_prospects_status ON prospects (status);

-- Seed the researched list. Safe to re-run: existing rows are left alone so
-- a re-run never clobbers outreach status the team has already recorded.
INSERT INTO prospects
  (tier, name, category, address, city, phone, phone_confidence, google_rating, product_angle, notes)
SELECT v.tier, v.name, v.category, v.address, v.city, v.phone, v.phone_confidence,
       v.google_rating, v.product_angle, v.notes
  FROM (VALUES
    ('A', 'First Baptist Church of Fairburn', 'Baptist church', '23 SE Malone St', 'Fairburn', '(770) 964-1431', 'verified', '4.8 (38)', 'Youth camp tees, VBS, choir robes/polos, anniversary tees', 'Runs music camp - annual tee opportunity'),
    ('A', 'Crossroads Church South Fulton', 'Church', '304 Fairburn Industrial Blvd', 'Fairburn', NULL, NULL, '4.8 (45)', 'Volunteer team shirts, outreach event tees, kids ministry', NULL),
    ('A', 'Harvest Rain Church International', 'Church', '8567 Bohannon Dr', 'Fairburn', '(770) 969-2040', 'verified', '4.9 (17)', 'Ministry tees, usher polos', 'Also operates Harvest Rain Early Learning Academy - bundle deal'),
    ('A', 'New City Church - Fairburn Campus', 'Christian church', '3355 Old Jonesboro Rd', 'Fairburn', '(470) 502-5198', 'verified', '4.9 (93)', 'Volunteer tees, serve-day shirts, kids check-in', 'Large congregation - also runs City Bridges Food Pantry'),
    ('A', 'Mt Zion Baptist Church', 'Baptist church', '120 S Greene St', 'Fairburn', '(770) 964-4425', 'verified', '4.9 (15)', 'Anniversary tees, usher board, choir', NULL),
    ('A', 'Cornerstone Fellowship Church', 'Church', '3310 Bethsaida Rd', 'Fairburn', NULL, NULL, '5.0 (51)', 'Volunteer + outreach apparel', NULL),
    ('A', 'Living Word Church Ministries', 'Church', '410 Senoia Rd', 'Fairburn', '(770) 964-5926', 'verify on call', '5.0 (8)', 'Ministry tees', NULL),
    ('A', 'JABEZ Church', 'Church', '7882 Senoia Rd', 'Fairburn', NULL, NULL, '5.0 (2)', 'Launch/branding tees', NULL),
    ('A', 'Temple of Prayer Family Worship Cathedral, UCOGIC', 'Church', '161 Senoia Rd', 'Fairburn', '(770) 969-5126', 'verified', '4.6 (33)', 'Convocation tees, usher uniforms', NULL),
    ('A', 'Fairburn United Methodist Church', 'Methodist church', '5 Washington St', 'Fairburn', '(770) 964-3393', 'verified', '4.8 (4)', 'Mission trip tees, community day', 'Downtown - walkable from Broad St'),
    ('A', 'St John AME Church', 'Methodist church', '305 W Campbellton St', 'Fairburn', NULL, NULL, '4.7 (22)', 'Church anniversary, usher board, youth dept', 'Historic Black congregation - strong community ties'),
    ('A', 'New Horizons In Faith Church International, Inc', 'Full Gospel church', '81 W Campbellton St', 'Fairburn', NULL, NULL, '4.8 (10)', 'Ministry apparel', NULL),
    ('A', 'Word of Love Christian Church', 'Church', '3650 Jonesboro Rd', 'Fairburn', NULL, NULL, '5.0 (11)', 'Ministry apparel', NULL),
    ('A', 'Welcome Grove Baptist Church', 'Baptist church', 'Fairburn', 'Fairburn', NULL, NULL, '4.5 (4)', 'Homecoming/anniversary tees', NULL),
    ('A', 'Miller Grove Baptist Church', 'Christian church', 'Fairburn', 'Fairburn', NULL, NULL, '5.0 (2)', 'Homecoming/anniversary tees', NULL),
    ('A', 'Bethlehem Baptist Church', 'Baptist church', '5485 Bethlehem Rd', 'Fairburn', '(770) 964-3007', 'verified', NULL, 'Anniversary + youth tees', 'From OSM/directory data'),
    ('A', 'Pleasant Hill Baptist Church', 'Baptist church', '125 Cedar Ln', 'Fairburn', NULL, NULL, NULL, 'Anniversary + youth tees', 'From directory data'),
    ('A', 'Mount Vernon Baptist Church', 'Baptist church', '5675 Campbellton Fairburn Rd', 'Fairburn', NULL, NULL, NULL, 'Anniversary + youth tees', NULL),
    ('A', 'Cedar Grove Church of Christ', 'Church', '9100 Clark Rd', 'Fairburn', '(770) 964-1744', 'verified', NULL, 'Ministry apparel', NULL),
    ('A', 'Calvary Church', 'Church', '7380 Bishop Rd', 'Fairburn', NULL, NULL, NULL, 'Ministry apparel', NULL),
    ('A', 'Open Word Christian Ministries', 'Church', '6230 GA 92', 'Fairburn', NULL, NULL, NULL, 'Ministry apparel', NULL),
    ('A', 'A Step At A Time Early Learning Academy', 'Child care agency', '204 Senoia Rd', 'Fairburn', NULL, NULL, '5.0 (64)', 'Staff polos, student tees, graduation shirts, field-trip safety tees', 'Two locations - strong repeat customer profile'),
    ('A', 'A Step At A Time Early Learning Academy 2', 'Day care center', '277 NE Broad St', 'Fairburn', NULL, NULL, '5.0 (8)', 'Same as location 1', 'Downtown Broad St'),
    ('A', 'Harvest Rain Early Learning Academy', 'Child care agency', '51 Senoia Rd', 'Fairburn', '(770) 969-2040', 'verified', '3.9 (17)', 'Staff polos, student tees, pre-K graduation', 'Tied to Harvest Rain Church - one relationship two accounts'),
    ('A', 'Byrd''s Nest Child Care Center', 'Day care center', '123 NE Broad St', 'Fairburn', NULL, NULL, '1.0 (2)', 'Staff polos, student tees', 'Downtown Broad St - low rating, may be small'),
    ('A', 'Tiny Friends Family ChildCare', 'Child care agency', '462 Pecan Wood Cir', 'Fairburn', NULL, NULL, '5.0 (12)', 'Staff + student tees', NULL),
    ('A', 'Tender Love & Care Quality', 'Day care center', '3705 Pointe Cir', 'Fairburn', NULL, NULL, '5.0 (1)', 'Staff + student tees', NULL),
    ('A', 'Walk Leap Grow Early Learning Center', 'Day care center', '6050 Landers Loop', 'Fairburn', NULL, NULL, '3.8 (15)', 'Staff polos, graduation tees', NULL),
    ('A', 'Selby''s 24HR Daycare', 'Day care center', '3150 White Tail Ln', 'Fairburn', NULL, NULL, '4.8 (28)', 'Staff polos, student tees', NULL),
    ('A', 'DreamBig Childcare', 'Day care center', '6001 Red Top Loop', 'Fairburn', NULL, NULL, '5.0 (1)', 'Staff + student tees', NULL),
    ('A', 'Alkin Academy Inc.', 'Day care center', '3620 Jonesboro Rd', 'Fairburn', NULL, NULL, '4.3 (50)', 'Staff polos, graduation tees', NULL),
    ('A', 'Lifetime Youth Learning Center LLC', 'Learning center', '5144 McKinley Ave', 'South Fulton', NULL, NULL, '4.9 (33)', 'Program tees, summer camp', NULL),
    ('A', 'Campbell Elementary School', 'Elementary school', '91 Elder St', 'Fairburn', '(770) 969-3430', 'verified', NULL, 'Spirit wear, PTA fundraiser tees, field day, staff shirts', 'Fulton County Schools - go through PTA not district'),
    ('A', 'Renaissance Elementary School', 'Elementary school', '7250 Hall Rd', 'Fairburn', '(470) 254-4320', 'verified', NULL, 'Spirit wear, PTA fundraisers, field day', NULL),
    ('A', 'Renaissance Middle School', 'Middle school', '7155 Hall Rd', 'Fairburn', '(470) 254-4330', 'verified', NULL, 'Spirit wear, club/team shirts', NULL),
    ('A', 'Bear Creek Middle School', 'Middle school', '7415 Herndon Rd', 'Fairburn', '(770) 969-6080', 'verify on call', NULL, 'Spirit wear, athletics, band', NULL),
    ('A', 'Creekside High School', 'High school', '7405 Herndon Rd', 'Fairburn', '(470) 254-4300', 'verified', NULL, 'Athletics, band, clubs, senior class tees, homecoming', 'Biggest single spirit-wear opportunity in the city'),
    ('A', 'Langston Hughes High School', 'High school', '7510 Hall Rd', 'Fairburn', '(470) 254-3620', 'verified', NULL, 'Athletics, band, clubs, senior tees', '470-254-3620'),
    ('A', 'Evoline C. West Elementary School', 'Elementary school', '7040 Rivertown Rd', 'Fairburn', '(770) 969-3460', 'verified', NULL, 'Spirit wear, PTA, field day', NULL),
    ('A', 'Global Impact Academy STEM Magnet High School', 'High school', '155 Shaw Dr', 'Fairburn', NULL, NULL, NULL, 'Club/competition team tees, STEM events', NULL),
    ('A', 'Landmark Christian School', 'Private K-12', '50 SE Broad St', 'Fairburn', '(770) 441-4238', 'verified', NULL, 'Athletics, spirit wear, uniforms', 'Private school - buys direct, no district red tape. High value.'),
    ('A', 'The Bedford School', 'Private school', '5665 Milam Rd', 'Fairburn', '(770) 774-8001', 'verified', NULL, 'Spirit wear, staff shirts', NULL),
    ('A', 'Fairburn Youth Center (900 Fairburn Youth Center)', 'Community center', '149 SW Broad St', 'Fairburn', '(770) 964-2244 x134', 'map listing', '4.5 (50)', 'Youth program tees, camp shirts, league jerseys', 'City-run - 770-964-2244 x134. Gateway to city rec programs.'),
    ('A', 'The Gathering Place Community Center', 'Community center', '6280 Bryant St', 'Union City', NULL, NULL, '4.6 (101)', 'Program + event tees', NULL),
    ('A', 'City Bridges Food Pantry - Fairburn Campus', 'Food bank', '3355 Old Jonesboro Rd', 'Fairburn', NULL, NULL, '4.5 (50)', 'Volunteer tees', 'Tied to New City Church'),
    ('A', 'Citizens of Fairburn United', 'Non-profit', '101 W Campbellton St # B', 'Fairburn', NULL, NULL, '5.0 (1)', 'Civic event tees, campaign apparel', 'Local civic group - connector to other orgs'),
    ('A', 'PROFICIENT FRONTLINE COMMUNITY SERVICES, Inc', 'Non-profit', 'Parkland Bend #7500', 'Fairburn', NULL, NULL, '5.0 (1)', 'Staff + volunteer apparel', NULL),
    ('A', 'BREAD OF LIFE OUTPOURING', 'Non-profit', '7860 Senoia Rd Ste c', 'Fairburn', NULL, NULL, NULL, 'Volunteer + outreach tees', NULL),
    ('A', 'Flying Change Equine Therapy', 'Non-profit / therapy', '9075 Gullatt Rd', 'Fairburn', NULL, NULL, NULL, 'Volunteer tees, fundraiser apparel, event merch', 'flyingchange.org'),
    ('A', 'Southside Theatre Guild', 'Community theatre', '18 W Campbellton St', 'Fairburn', NULL, NULL, NULL, 'Cast/crew shirts, show merch, season tees', 'Downtown - recurring per-production orders'),
    ('A', 'Georgia Renaissance Festival', 'Festival / event', 'Renaissance Pkwy', 'Fairburn', NULL, NULL, NULL, 'Staff shirts, vendor apparel, event merch', 'Massive seasonal event - already has a merch shop. Neighbor to your shop.'),
    ('A', 'Sugahplum Events', 'Event venue', '2220 Jonesboro Rd #107', 'Fairburn', NULL, NULL, '4.5 (147)', 'Staff shirts, client event merch', 'Also a referral channel - they see every party planner'),
    ('A', 'Elegant Occasions Event Center', 'Event venue', '7580 Springbox Dr #100', 'Fairburn', '(404) 838-7150', 'verified', '4.5 (121)', 'Staff shirts, client event merch', 'Referral channel for reunions/birthdays'),
    ('A', 'Igbo Event Center', 'Event venue', '7090 Oakley Industrial Blvd', 'Fairburn', NULL, NULL, '5.0 (1)', 'Cultural event tees, family reunion apparel', 'Cultural org events = large group orders'),
    ('A', 'South Fulton Studios', 'Dance school', '29 SW Broad St', 'Fairburn', NULL, NULL, '4.4 (30)', 'Recital tees, competition team apparel, warmups', 'Downtown. Dance studios reorder every season.'),
    ('A', 'IAMCHARDE TUMBLING', 'Gym / tumbling', '7580 Springbox Dr Ste 240', 'Fairburn', NULL, NULL, '4.8 (48)', 'Team tees, meet shirts, parent apparel', NULL),
    ('A', 'The Gym 24/7 Fitness', 'Gym', '8460 Senoia Rd', 'Fairburn', NULL, NULL, '4.6 (163)', 'Member tees, staff shirts, challenge/event apparel', NULL),
    ('A', 'South Fulton Fit Body Boot Camp', 'Fitness center', '7580 Springbox Dr Ste 240', 'Fairburn', NULL, NULL, '5.0 (20)', 'Challenge tees, member swag', 'Bootcamps run transformation challenges = batch tee orders'),
    ('A', 'Tri-Phase Total Fitness', 'Fitness program', '6000 Lynmark Way', 'Fairburn', NULL, NULL, '5.0 (2)', 'Client tees', NULL),
    ('A', 'Diamond Action Design Studio', 'Gym', '89 Howell Ave', 'Fairburn', NULL, NULL, '5.0 (3)', 'Studio tees', NULL),
    ('A', 'Hero Roofing', 'Roofing contractor', '21 Tower Pl', 'Fairburn', NULL, NULL, '4.9 (829)', 'Crew safety tees, hi-vis, hoodies, hats, job-site branding', '829 reviews = large crew. TOP CONTRACTOR PROSPECT.'),
    ('A', 'Plumb Ready Plumbing', 'Plumber', '130 Howell Rd C', 'Fairburn', '(470) 243-1234', 'verified', '5.0 (501)', 'Crew uniforms, embroidered polos, work shirts', '501 reviews = high volume operation'),
    ('A', 'RCP Plumbing, LLC', 'Plumber', '441 Gage Hill Ln', 'Fairburn', '(404) 670-0043', 'verified', '4.8 (87)', 'Crew uniforms, embroidered polos', NULL),
    ('A', 'Fairburn Roofing and Gutters', 'Roofing contractor', '334 Cog Hill Dr', 'Fairburn', NULL, NULL, '5.0 (3)', 'Crew tees, hi-vis', 'Fairburn in the name - lean into local pride'),
    ('A', 'Smith Roofing & Construction', 'Roofing contractor', '6155 Dodson Rd', 'Fairburn', '(404) 454-5870', 'verified', '4.9 (16)', 'Crew tees, hi-vis, hats', NULL),
    ('A', 'Exceptional Home Remodeling & Landscaping', 'Contractor', '7532 Parkland Bend', 'Fairburn', NULL, NULL, NULL, 'Crew tees, hi-vis, hats', NULL),
    ('A', 'Gowen''s Automotive Repair', 'Auto repair', '28 Dodd St', 'Fairburn', '(770) 964-2455', 'verified', '4.4 (511)', 'Mechanic work shirts, embroidered names, shop tees', '511 reviews - established local institution'),
    ('A', 'Jerry Gowens Garage', 'Auto repair', '20 NW Broad St', 'Fairburn', '(770) 964-8526', 'verified', '4.5 (85)', 'Work shirts, shop tees', 'Downtown Broad St'),
    ('A', 'Fairburn Emission & Automotive', 'Auto repair', '418 SE Broad St', 'Fairburn', NULL, NULL, '4.4 (223)', 'Work shirts, shop tees', NULL),
    ('A', 'Fairburn Automotive', 'Auto repair', '238 NW Broad St', 'Fairburn', '(770) 306-2339', 'map listing', NULL, 'Work shirts, shop tees', '770-306-2339 / fairburnautomotive.com'),
    ('A', 'Fairburn Tire & Service', 'Truck repair', '7860 Senoia Rd Ste d', 'Fairburn', '(770) 964-0669', 'verify on call', '4.1 (17)', 'Work shirts, shop tees', NULL),
    ('A', 'TONY THE DETAIL GUY', 'Car detailing', '425 Senoia Rd', 'Fairburn', NULL, NULL, '4.9 (50)', 'Branded tees, hats, towels', 'Detailers love branded merch for social media'),
    ('A', 'Roadside on Demand LLC', 'Tire/roadside service', '330 Riverview Ct', 'Fairburn', '(855) 771-7100', 'verified', '4.9 (49)', 'Hi-vis crew shirts, hats', NULL),
    ('A', 'Triple Rrr Roadside Assistances', 'Tire repair', '6104 Park Close', 'Fairburn', NULL, NULL, '4.9 (105)', 'Hi-vis crew shirts', NULL),
    ('A', 'Mr L Clark Towing Transportation and Recovery', 'Towing', '4885 Locherby Dr', 'Fairburn', NULL, NULL, '4.8 (95)', 'Driver uniforms, hi-vis, hats', NULL),
    ('A', 'Handsome Hair Barber Shop', 'Barber shop', '7860 Senoia Rd', 'Fairburn', '(770) 306-8989', 'verified', '3.9 (24)', 'Shop tees, capes, barber aprons, hats', NULL),
    ('A', 'FreeKings Cuts', 'Barber shop', '8274 Champion Trail', 'Fairburn', NULL, NULL, '4.8 (98)', 'Shop tees, hats, aprons', '98 reviews - busy shop, strong brand'),
    ('A', 'FADE AWAY BARBER SHOP', 'Barber shop', '8390 Senoia Rd', 'Fairburn', NULL, NULL, '4.7 (14)', 'Shop tees, aprons', NULL),
    ('A', 'Thetransformationbarber', 'Barber shop', '8390 Senoia Rd', 'Fairburn', NULL, NULL, '5.0 (13)', 'Personal brand tees, hats', 'Same building as Fade Away - two-for-one visit'),
    ('A', 'El Milagro Hair Salon #1', 'Barber shop', '263 Senoia Rd', 'Fairburn', NULL, NULL, '4.3 (86)', 'Shop tees, capes', 'Spanish-language marketing may help'),
    ('A', 'Your Natural Hair Place', 'Hair salon', '274 Senoia Rd Ste. #2', 'Fairburn', NULL, NULL, '4.5 (26)', 'Salon tees, aprons, client merch', NULL),
    ('A', 'Elegant Expressions Beauty And Styles Salon', 'Beauty salon', '7794 Ella Ln Ste c', 'Fairburn', NULL, NULL, '4.9 (72)', 'Salon tees, aprons, capes', NULL),
    ('A', 'Kkutz Atl', 'Barber shop', 'Camden Way', 'Fairburn', NULL, NULL, '5.0 (2)', 'Personal brand tees', NULL),
    ('B', 'Judy''s Restaurant', 'Restaurant', 'Fairburn', 'Fairburn', '(770) 964-0820', 'verify on call', '4.5 (718)', 'Staff tees/aprons, retail merch tees for regulars', '718 reviews - local landmark. Retail merch potential.'),
    ('B', 'The Dining Experience', 'Restaurant', 'Fairburn', 'Fairburn', NULL, NULL, '4.4 (548)', 'Staff aprons + branded tees', NULL),
    ('B', 'TrucKINGS bbq', 'BBQ restaurant', 'Fairburn', 'Fairburn', NULL, NULL, '4.7 (396)', 'Staff tees, retail merch, catering event shirts', 'BBQ brands sell merch well - pitch retail line'),
    ('B', 'Lady Fannie Mae''s Ultimate Fish Fry', 'Restaurant', 'Fairburn', 'Fairburn', NULL, NULL, '4.3 (375)', 'Staff tees, retail merch', NULL),
    ('B', 'Unbelievegan', 'Vegan restaurant', '7000 Renaissance Pkwy', 'Fairburn', '(678) 489-6969', 'map listing', '4.5 (111)', 'Staff tees, retail merch', '678-489-6969. Strong brand identity = merch buyers.'),
    ('B', 'The Peach Cobbler Factory of Fairburn', 'Dessert shop', '8026 Senoia Rd', 'Fairburn', '(678) 586-5031', 'map listing', '4.7 (340)', 'Staff tees, aprons', '678-586-5031. Franchise - check corporate rules.'),
    ('B', 'Ms. Savory Restaurant & Catering LLC', 'Restaurant / caterer', 'Fairburn', 'Fairburn', NULL, NULL, '4.3 (71)', 'Staff tees, catering crew shirts', 'Caterers need crew shirts for every event'),
    ('B', 'Clark''s Signature Kitchen', 'Soul food', '123 Oak St', 'Fairburn', NULL, NULL, '5.0 (2)', 'Staff tees, merch', NULL),
    ('B', 'Don Nachos Fairburn', 'Mexican restaurant', 'Fairburn', 'Fairburn', NULL, NULL, '4.1 (291)', 'Staff tees, aprons', NULL),
    ('B', 'Los Mariachis Mexican Restaurant', 'Mexican restaurant', 'Fairburn', 'Fairburn', '(770) 703-8376', 'verify on call', '4.0 (2278)', 'Staff tees, aprons', '2278 reviews - very high traffic'),
    ('B', 'Muchacho Alegre', 'Mexican restaurant', 'Fairburn area', 'Fairburn', '(770) 629-2528', 'verify on call', '4.5 (306)', 'Staff tees, aprons', NULL),
    ('B', 'Dragon House Restaurant', 'Chinese restaurant', 'Fairburn area', 'Fairburn', '(770) 306-5538', 'verify on call', '3.8 (410)', 'Staff tees', NULL),
    ('B', 'Golden Krust Caribbean Restaurant', 'Caribbean restaurant', 'Fairburn area', 'Fairburn', '(770) 703-7498', 'verify on call', '4.3 (996)', 'Staff tees', 'Franchise - check corporate rules'),
    ('B', '6340 EATS', 'Restaurant', '6340 Koweta Rd', 'Fairburn', NULL, NULL, '5.0 (1)', 'Staff tees, merch', NULL),
    ('B', 'Oz Pizza', 'Pizza', '5 SW Broad St', 'Fairburn', '(770) 306-0603', 'verified', NULL, 'Staff tees, delivery driver shirts', '770-306-0603. Downtown.'),
    ('B', 'Drunk Monk Pub', 'Pub', 'Fairburn', 'Fairburn', NULL, NULL, NULL, 'Staff tees, retail merch, trivia-night shirts', NULL),
    ('B', 'Peacock Tea Room', 'Tea room', 'Fairburn', 'Fairburn', NULL, NULL, NULL, 'Staff aprons, event merch', NULL),
    ('B', 'Fairburn Insurance', 'Insurance agency', '130 Washington St', 'Fairburn', NULL, NULL, '4.6 (8)', 'Staff polos, community sponsorship tees', 'Local agencies sponsor youth teams - double opportunity'),
    ('B', 'T W Smith Insurance', 'Insurance agency', '19 W Campbellton St', 'Fairburn', NULL, NULL, '5.0 (6)', 'Staff polos, sponsorship tees', NULL),
    ('B', 'David''s Insurance', 'Insurance agency', '13 Smith St', 'Fairburn', NULL, NULL, '4.3 (8)', 'Staff polos, sponsorship tees', NULL),
    ('B', 'Ac Income Tax Multiservices Insurance Agency', 'Insurance agency', '216 NW Broad St', 'Fairburn', '(678) 933-4000', 'verified', '5.0 (2)', 'Staff polos, tax-season promo tees', NULL),
    ('B', 'Serious Injury Law Group', 'Attorney', '4 NW Broad St', 'Fairburn', '(678) 268-6578', 'verify on call', '4.9 (32)', 'Staff polos, community sponsorship, giveaway tees', 'Law firms buy giveaway merch + sponsor events'),
    ('B', 'Russell T. Ross, Jr.', 'Legal services', '7 NW Broad St', 'Fairburn', NULL, NULL, '5.0 (1)', 'Staff polos', NULL),
    ('B', 'Fairburn Family Dentistry', 'Dentist', '168 NW Broad St', 'Fairburn', '(770) 964-1545', 'verify on call', '4.3 (29)', 'Staff scrubs/polos, kids giveaway tees, toothbrush-club shirts', NULL),
    ('B', 'Dr. Robert L. White Jr, DDS', 'Dentist', '168 NW Broad St', 'Fairburn', NULL, NULL, '3.6 (16)', 'Staff polos', 'Same building as Fairburn Family Dentistry'),
    ('B', 'Exquisite Smiles', 'Cosmetic dentist', '5370 Campbellton Fairburn Rd #130', 'Fairburn', '(770) 964-0494', 'verify on call', '3.7 (45)', 'Staff polos, patient giveaways', NULL),
    ('B', 'Animal Medical Clinic of Fairburn', 'Veterinary', '8520 Senoia Rd', 'Fairburn', '(770) 692-6034', 'verified', NULL, 'Staff scrubs/polos, client merch, adoption-event tees', '770-692-6034'),
    ('B', 'Piedmont Urgent Care', 'Urgent care', '8028 Senoia Rd', 'Fairburn', NULL, NULL, NULL, 'Staff polos', NULL),
    ('B', 'Family Medical Center', 'Clinic', 'Fairburn', 'Fairburn', NULL, NULL, NULL, 'Staff polos/scrubs', NULL),
    ('B', 'United Community Bank', 'Bank', '65 Washington St', 'Fairburn', NULL, NULL, NULL, 'Staff polos, community event sponsorship tees', 'Banks sponsor local festivals - pitch event merch'),
    ('B', 'Lavish Nail Bar Fairburn', 'Nail salon', '8026 Senoia Rd Ste 102', 'Fairburn', '(470) 278-8808', 'verified', '4.3 (168)', 'Staff tees, client merch', NULL),
    ('B', 'VIBE NAIL BAR FAIRBURN', 'Nail salon', '7895 Senoia Rd', 'Fairburn', NULL, NULL, '4.8 (975)', 'Staff tees, branded merch', '975 reviews - biggest nail salon in town, strong brand'),
    ('B', 'Diamond Nails & Spa of Fairburn', 'Nail salon', '8030 Senoia Rd Ste 300', 'Fairburn', '(770) 964-0034', 'verified', '3.4 (257)', 'Staff tees', NULL),
    ('B', 'Nicest Nails', 'Nail salon', '7794 Ella Ln #F', 'Fairburn', NULL, NULL, '3.6 (276)', 'Staff tees', NULL),
    ('B', 'Lucky Nails', 'Nail salon', '17 Hudson Plz Ste A', 'Fairburn', '(770) 774-7104', 'verified', '4.3 (644)', 'Staff tees', NULL),
    ('B', 'Natural Nails', 'Nail salon', '6015 Lynmark Way', 'Fairburn', '(770) 774-1127', 'verified', '3.3 (76)', 'Staff tees', NULL),
    ('B', 'Nail Chaos Studio', 'Nail salon', '1155 Senoia Rd Ste 103', 'Fairburn', NULL, NULL, '5.0 (19)', 'Branded merch', NULL),
    ('B', 'Tractor Supply Company', 'Farm/ranch retail', '8015 Senoia Rd', 'Fairburn', '(770) 964-2082', 'verified', NULL, 'Local store event tees', '770-964-2082. Corporate chain - store-level events only.'),
    ('C', 'GEODIS', 'Warehouse/3PL', '4955 Oakley Industrial Blvd', 'Fairburn', NULL, NULL, '2.4 (152)', 'Safety hi-vis tees, employee appreciation, safety-milestone shirts', 'Oakley Industrial corridor. Ask for HR / Site Safety Manager.'),
    ('C', 'DHL Supply Chain', 'Warehouse/3PL', '1555 Oakley Industrial Blvd', 'Fairburn', NULL, NULL, '3.9 (26)', 'Safety tees, employee appreciation', 'Ask for HR / Site Manager'),
    ('C', 'The Clorox Company', 'Warehouse', '1595 Oakley Industrial Blvd', 'Fairburn', NULL, NULL, '2.9 (459)', 'Safety milestone tees, employee events', 'Large headcount'),
    ('C', 'CJ Logistics America', 'Warehouse/3PL', '5000A Bohannon Rd', 'Fairburn', NULL, NULL, '2.9 (376)', 'Safety tees, employee appreciation', NULL),
    ('C', 'GXO', 'Warehouse/3PL', '7310 & 7300 & 6705 & 1525 Oakley Industrial Blvd', 'Fairburn', NULL, NULL, '3.2-4.1', 'Safety tees, employee appreciation', 'FOUR separate Fairburn sites - one relationship, multiple orders'),
    ('C', 'Maersk', 'Warehouse', '7280 Oakley Industrial Blvd', 'Fairburn', NULL, NULL, '3.7 (84)', 'Safety tees, employee events', NULL),
    ('C', 'Samsung Electronics America', 'Warehouse', '1525 Oakley Industrial Blvd', 'Fairburn', NULL, NULL, '2.6 (85)', 'Employee event tees', NULL),
    ('C', 'SC Johnson & Son Inc', 'Distribution', '1555 Oakley Industrial Blvd', 'Fairburn', NULL, NULL, '3.4 (165)', 'Safety + employee appreciation tees', NULL),
    ('C', 'NFI Industries Inc', 'Warehouse', '2000 Logistics Center Dr', 'Fairburn', NULL, NULL, '4.4 (7)', 'Safety tees', NULL),
    ('C', 'AIT Worldwide Logistics', 'Logistics', '6725 Oakley Industrial Blvd Suite 100', 'Fairburn', NULL, NULL, '3.1 (81)', 'Safety + staff apparel', NULL),
    ('C', 'Menlo Worldwide Logistics', 'Warehouse', '6705 Oakley Industrial Blvd', 'Fairburn', NULL, NULL, '3.1 (8)', 'Safety tees', NULL),
    ('C', 'International Truck & Engine Distribution Center', 'Warehouse', '1300 Oakley Industrial Blvd', 'Fairburn', NULL, NULL, '4.5 (18)', 'Safety + staff apparel', NULL),
    ('C', 'Crossdock 24/7 Atlanta', 'Warehouse', '605 Bohannon Rd Doors 7-9', 'Fairburn', NULL, NULL, '5.0 (31)', 'Driver + crew shirts', 'Smaller operator - easier decision maker'),
    ('C', 'FAIRBURN WAREHOUSE', 'Warehouse', '5025 Fayetteville Rd Ste B', 'Fairburn', NULL, NULL, '2.3 (15)', 'Crew shirts', NULL),
    ('C', 'Fairburn Logistics Center', 'Logistics', '2000 Logistics Center Dr', 'Fairburn', NULL, NULL, '3.8 (17)', 'Crew shirts', NULL),
    ('C', 'Material In Motion', 'Non-profit / logistics', '1000 Logistics Center Dr', 'Fairburn', NULL, NULL, NULL, 'Volunteer + staff tees', 'materialinmotion.com - nonprofit, volunteer events'),
    ('C', 'ADESA Atlanta', 'Auto auction', 'Fairburn', 'Fairburn', NULL, NULL, NULL, 'Staff shirts, auction event tees', 'Large employer'),
    ('C', 'Manheim Atlanta', 'Auto auction', 'Fairburn', 'Fairburn', NULL, NULL, NULL, 'Staff shirts, auction event tees', 'Large employer'),
    ('C', 'Durham Lakes Country Club', 'Golf course', 'Fairburn', 'Fairburn', NULL, NULL, NULL, 'Tournament tees/polos, staff uniforms, pro-shop merch', 'Golf tournaments = recurring polo orders. HIGH VALUE despite C tier.'),
    ('C', 'City of Fairburn', 'Municipality', '56 Malone St', 'Fairburn', '(770) 964-2244', 'map listing', NULL, 'Staff uniforms, city event tees, parks & rec leagues, festivals', '770-964-2244. Main Street office x172. Requires vendor registration.'),
    ('C', 'Fairburn Main Street / DDA', 'Downtown org', 'Fairburn', 'Fairburn', '(770) 964-2244 x172', 'map listing', NULL, 'Festival merch, downtown event tees, merchant campaign', '770-964-2244 x172. Gateway to every downtown merchant.'),
    ('C', 'Greater South Fulton Chamber of Commerce', 'Chamber', '4405 Mall Blvd Ste 120', 'Union City', '(770) 964-1984', 'map listing', NULL, 'Chamber event tees, member directory access', '770-964-1984. JOIN THIS - instant access to member list.')
  ) AS v(tier, name, category, address, city, phone, phone_confidence,
         google_rating, product_angle, notes)
 WHERE NOT EXISTS (SELECT 1 FROM prospects p WHERE p.name = v.name);
